# Generated by Django 4.2 on 2023-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DomainEyeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='temps',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
